apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: demo-voting-app
        name: result-pod
    spec:
      containers:
        - name: voting-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
