apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        app: demo-voting-app
        name: voting-pod
    spec:
      containers:
        - name: voting-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
